baseURL = "/"
languageCode = "en-us"
title = "ASTRO CYCLES"
theme = "hugo-starter"
pluralizeListTitles = false

[Params]
    mainSections = ["posts"]
    intro = true
    headline = "My headline"
    description = "My description"
    # github = "https://github.com/XXX"
    # twitter = "https://twitter.com/XXX"
    # email = "XXX@example.com"
    opengraph = false
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2007"
    math = true

[Permalinks]
    post = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "Mercury"
    name = '1. Mercury'
    url = "/mercury"
    weight = 10

  [[menu.main]]
    identifier = "Venus"
    name = "2. Venus"
    url = "/venus"
    weight = 20

  [[menu.main]]
    identifier = "Earth"
    name = "3. Earth"
    url = "/earth"
    weight = 30

  [[menu.main]]
    identifier = "Mars"
    name = "4. Mars"
    url = "/mars"
    weight = 40
    
  [[menu.main]]
    identifier = "Jupiter"
    name = "5. Jupiter"
    url = "/jupiter"
    weight = 50

  [[menu.main]]
    identifier = "Saturn"
    name = "6. Saturn"
    url = "/saturn"
    weight = 60

  [[menu.main]]
    identifier = "Uranus"
    name = "7. Uranus"
    url = "/uranus"
    weight = 70

  [[menu.main]]
    identifier = "Neptune"
    name = "8. Neptune"
    url = "/neptune"
    weight = 80

  [[menu.main]]
    identifier = "Pluto"
    name = "9. Pluto"
    url = "/pluto"
    weight = 90

