baseURL = "/"
languageCode = "en-us"
title = "MARS' CYCLES"
theme = "hugo-starter"
pluralizeListTitles = false

[Params]
    mainSections = ["posts"]
    intro = true
    headline = "My headline"
    description = "My description"
    # github = "https://github.com/XXX"
    # twitter = "https://twitter.com/XXX"
    # email = "XXX@example.com"
    opengraph = false
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2007"
    math = true

[Permalinks]
    post = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "Timecycle"
    name = "1. by TIMECYCLE"
    url = "mars/1.Timecycle"
    weight = 10

  [[menu.main]]
    identifier = "Phase"
    name = "2. PHASE"
    url = "/mars/2.Phase"
    weight = 20

  [[menu.main]]
    identifier = "Orbit"
    name = "3. ORBIT"
    url = "/mars/3.Orbit"
    weight = 30

  [[menu.main]]
    identifier = "Moonth"
    name = "4. MOONTH"
    url = "/mars/4.Moonth"
    weight = 40

  [[menu.main]]
    identifier = "Itself"
    name = "5. ITSELF"
    url = "/mars/5.Itself"
    weight = 50
    
  [[menu.main]]
    identifier = "Sky"
    name = "6. SKY"
    url = "/mars/6.Sky"
    weight = 60

  [[menu.main]]
    identifier = "Phenomena"
    name = "7. by PHENOMENA"
    url = "/mars/7.Phenomena"
    weight = 70

